<div>
<h1 <h1 style="text-align: center;font-family : Serif; background : #c012; color: #176bea";>Student Performance Analysis</h1>
</div>

<div>
  <h2 style='color: #58a6ff; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 1.3 em;'>Importing Necessary Libraries</h2>
  
</div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker

sns.set_theme(style='darkgrid', palette='muted')
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.family'] = 'DejaVu Sans'

print('Libraries loaded successfully ')

Libraries loaded successfully

<div>
  <h2 style='color: #58a6ff; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 1.3 em;'>Load Dataset</h2>
  
</div>

In [4]:
data = pd.read_csv(r"C:\Muhammad Qasim Ashfaq\University A\Artificial Intelligence\LAB AI\Artificial Intelligence LAB-TASK 10\Student_performance_data __.csv")

print(f"Shape: {data.shape}")
print(f'\nColumn names:')
for col in data.columns:
    print(f'  → {col}')

Shape: (2392, 15)

Column names:
  → StudentID
  → Age
  → Gender
  → Ethnicity
  → ParentalEducation
  → StudyTimeWeekly
  → Absences
  → Tutoring
  → ParentalSupport
  → Extracurricular
  → Sports
  → Music
  → Volunteering
  → GPA
  → GradeClass

In [5]:
data.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
5,1006,18,0,0,1,8.191219,0,0,1,1,0,0,0,3.084184,1.0
6,1007,15,0,1,1,15.601680,10,0,3,0,1,0,0,2.748237,2.0
7,1008,15,1,1,4,15.424496,22,1,1,1,0,0,0,1.360143,4.0
8,1009,17,0,0,0,4.562008,1,0,2,0,1,0,1,2.896819,2.0
9,1010,16,1,0,1,18.444466,0,0,3,1,0,0,0,3.573474,0.0

In [6]:
data.tail(5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

<div>
  <h2 style='color: #2fb6f5; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 2.0 em;'>Data Types & Structure</h2>
  
</div>

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [14]:
print("Data Types:")
print(data.dtypes)
memory_usage = data.memory_usage(deep=True).sum()/1024
print(f"\nMemory usage is: {round(memory_usage)}KB")

Data Types:
StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object

Memory usage is: 280KB

<div>
<h1 <h1 style="text-align: center;font-family : Serif; background : #c012; color: #176bea";>Missing Values & Duplicates [LAB TASK 10]</h1>
</div>

In [17]:
missing_values = data.isnull().sum()
print("Missing values in each column:")
for col, count in missing_values.items():
    print(f"  → {col}: {count}")

Missing values in each column:
  → StudentID: 0
  → Age: 0
  → Gender: 0
  → Ethnicity: 0
  → ParentalEducation: 0
  → StudyTimeWeekly: 0
  → Absences: 0
  → Tutoring: 0
  → ParentalSupport: 0
  → Extracurricular: 0
  → Sports: 0
  → Music: 0
  → Volunteering: 0
  → GPA: 0
  → GradeClass: 0

In [18]:
duplicates = data.duplicated().sum()
print(f"Duplicate rows: {duplicates}")
print(f"Unique StudentIDs: {data["StudentID"].nunique()}")
print(f"Total rows: {len(data)}")

Duplicate rows: 0
Unique StudentIDs: 2392
Total rows: 2392

<div 
  <h2 style='color: #41acee; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 1.8em;'>Descriptive Statistics</h2>
  
</div>

In [19]:
data.describe().round(3)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000,2392.000
mean,2196.500,16.469,0.511,0.878,1.746,9.772,14.541,0.301,2.122,0.383,0.304,0.197,0.157,1.906,2.984
std,690.655,1.124,0.500,1.028,1.000,5.653,8.467,0.459,1.123,0.486,0.460,0.398,0.364,0.915,1.234
min,1001.000,15.000,0.000,0.000,0.000,0.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,1598.750,15.000,0.000,0.000,1.000,5.043,7.000,0.000,1.000,0.000,0.000,0.000,0.000,1.175,2.000
50%,2196.500,16.000,1.000,0.000,2.000,9.705,15.000,0.000,2.000,0.000,0.000,0.000,0.000,1.893,4.000
75%,2794.250,17.000,1.000,2.000,2.000,14.408,22.000,1.000,3.000,1.000,1.000,0.000,0.000,2.622,4.000
max,3392.000,18.000,1.000,3.000,4.000,19.978,29.000,1.000,4.000,1.000,1.000,1.000,1.000,4.000,4.000

In [22]:
print("Key Observations:")
print(f"  Average GPA       : {data["GPA"].mean().round(2)}")
print(f"  Median GPA        : {data["GPA"].median().round(2)}")
print(f"  GPA Std Dev       : {data["GPA"].std().round(2)}")
print(f"  Avg Study Hrs/wk  : {data["StudyTimeWeekly"].mean().round(2)}")
print(f"  Avg Absences      : {data["Absences"].mean().round(2)}")
print(f"  Age Range         : {data["Age"].min()} - {data['Age'].max()}")

Key Observations:
  Average GPA       : 1.91
  Median GPA        : 1.89
  GPA Std Dev       : 0.92
  Avg Study Hrs/wk  : 9.77
  Avg Absences      : 14.54
  Age Range         : 15 - 18

<div 
  <h2 style='color: #58c2f7; font-family: Serif, sans-serif; font-size: 1.8em;'>Categorical Feature Analysis</h2>
 
</div>

In [28]:
column = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GradeClass']

for col in column:
    print(f'\n{col}:')
    v_count = data[col].value_counts().sort_index()
    for val, count in v_count.items():
        print(f"  {val} → {count} students ({round((count/len(data)*100), 2)}%)")

Gender:
  0 → 1170 students (48.91%)
  1 → 1222 students (51.09%)

Ethnicity:
  0 → 1207 students (50.46%)
  1 → 493 students (20.61%)
  2 → 470 students (19.65%)
  3 → 222 students (9.28%)

ParentalEducation:
  0 → 243 students (10.16%)
  1 → 728 students (30.43%)
  2 → 934 students (39.05%)
  3 → 367 students (15.34%)
  4 → 120 students (5.02%)

Tutoring:
  0 → 1671 students (69.86%)
  1 → 721 students (30.14%)

ParentalSupport:
  0 → 212 students (8.86%)
  1 → 489 students (20.44%)
  2 → 740 students (30.94%)
  3 → 697 students (29.14%)
  4 → 254 students (10.62%)

Extracurricular:
  0 → 1475 students (61.66%)
  1 → 917 students (38.34%)

Sports:
  0 → 1666 students (69.65%)
  1 → 726 students (30.35%)

Music:
  0 → 1921 students (80.31%)
  1 → 471 students (19.69%)

Volunteering:
  0 → 2016 students (84.28%)
  1 → 376 students (15.72%)

GradeClass:
  0.0 → 107 students (4.47%)
  1.0 → 269 students (11.25%)
  2.0 → 391 students (16.35%)
  3.0 → 414 students (17.31%)
  4.0 → 1211 students (50.63%)

<div 
  <h2 style='color: #79c0ff; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 1.8em;'>Changing the DataType of Column </h2>  
</div>

In [29]:
print("Original dtype:", data['StudyTimeWeekly'].dtype)

Original dtype: float64

In [30]:
data["StudyTimeWeekly"]=data["StudyTimeWeekly"].astype(int)
print("After conversion:", data["StudyTimeWeekly"].dtype)

After conversion: int64