<div>
<h1 <h1 style="text-align: center;font-family : Serif; background : #c012; color: #176bea";>Student Performance Analysis</h1>
</div>

<div>
  <h2 style='color: #58a6ff; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 1.3 em;'>Importing Necessary Libraries</h2>
  
</div>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print('Libraries loaded successfully ')

Libraries loaded successfully

<div>
  <h2 style='color: #58a6ff; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 1.3 em;'>Load Dataset</h2>
  
</div>

In [ ]:
data = pd.read_csv(r"C:\Muhammad Qasim Ashfaq\University A\Artificial Intelligence\LAB AI\Artificial Intelligence LAB-TASK 9\Student_performance_data __.csv")

print(f"Shape: {data.shape}")
print(f'\nColumn names:')
for col in data.columns:
    print(f'  → {col}')

Shape: (2392, 15)

Column names:
  → StudentID
  → Age
  → Gender
  → Ethnicity
  → ParentalEducation
  → StudyTimeWeekly
  → Absences
  → Tutoring
  → ParentalSupport
  → Extracurricular
  → Sports
  → Music
  → Volunteering
  → GPA
  → GradeClass

In [5]:
data.head(10)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
5,1006,18,0,0,1,8.191219,0,0,1,1,0,0,0,3.084184,1.0
6,1007,15,0,1,1,15.601680,10,0,3,0,1,0,0,2.748237,2.0
7,1008,15,1,1,4,15.424496,22,1,1,1,0,0,0,1.360143,4.0
8,1009,17,0,0,0,4.562008,1,0,2,0,1,0,1,2.896819,2.0
9,1010,16,1,0,1,18.444466,0,0,3,1,0,0,0,3.573474,0.0

In [6]:
data.tail(5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

<div>
  <h2 style='color: #2fb6f5; font-family: Serif, sans-serif; margin: 0 0 6px 0; font-size: 2.0 em;'>Data Types & Structure</h2>
  
</div>

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [14]:
print("Data Types:")
print(data.dtypes)
memory_usage = data.memory_usage(deep=True).sum()/1024
print(f"\nMemory usage is: {round(memory_usage)}KB")

Data Types:
StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object

Memory usage is: 280KB